### Matrix Math Notes 
+ The first matrix needs the same number of columns as the second matrix has rows.
+ 2x2 matrix (A) by 2x1 matrix (B) (The tw0 inner rows have to match)
+ The final matrix will have as many rows as the first matrix, and as many columns as the second matrix. 
+ The result matrix will always have the same number of rows as the first matrix being multiplied has columns, and the same number of columns as the second matrix being multiplied has rows.
+ If this dish is a schnitzel then it contains pork is––always true.
If this dish contains pork then it is a schnitzel––not always
+ matrix multiplication: result is **inside** values: 3x2 * 2x3 = 2x2
    + 3x2 * 2x4 = 2x2
    + 1x2 * 2x4 = 2x2
    + 4x4 * 4x2 = 4x4

+ Note: That 4 Page Linear Algebra doc was _written by a bot and/or masochist_

### Reading Vectors

+ first vector starts at 0,0 goes over 2 and up 0
+ second vector starts at 2,0 goes over 0 and up 3
+ third vector starts at 0,0 goes over 2 and up 3
```
X = [0,2,0] 
Y = [0,0,0]
U = [2,0,2] 
V = [0,3,3]
```

### Simple Vector
vectors are magnitudes--no coordinates
The below is goes 1 over in the X direction and 2 Up in the Y direction. The origin point could be anywhere
$$
\begin{bmatrix}
1 \\ 2
\end{bmatrix}
$$


---

## 1. Matrix Dimensions
Write the dimensions of each matrix.

### Matrix Dimension A
dimension: 2x3

$$
\begin{bmatrix} 
1&2&3 \\ 2&4&7
\end{bmatrix}
$$


### Matrix Dimension B
dimension: 2x2

$$
\begin{bmatrix} 
1 & -1 \\ 0 & 1
\end{bmatrix}
$$


### Matrix Dimension C
dimension: 3x2
$$
\begin{bmatrix} 
5 & -1 \\ 
9 & 1  \\ 
6 & 0
\end{bmatrix}
$$


### Matrix Dimension D
dimension: 2x3
$$
\begin{bmatrix} 
3 & -2 & -1 \\
1 & 2 & 3   \\
\end{bmatrix}
$$

### Matrix Dimension u
dimension: 1x4
$$
\begin{bmatrix} 
6 & 2 & -3 & 5 
\end{bmatrix}
$$

### Matrix Dimension w
dimension: 4x1
$$
\begin{bmatrix} 
1 \\
8 \\
0 \\
5 
\end{bmatrix}
$$

* * *



# 2. Vector Operations
Perform the following operations. Assume α = 6.

### 2.1) &nbsp;&nbsp; $\vec{u} + \vec{v} =$  


In [49]:
import numpy as np
u = np.asarray([6,2,-3,5])
v = np.asarray([3,5,-1,4])

calc = u + v
by_hand =  [(6+3),(2+5), (-3+-1), (5+4)]

print("calculated: {0} by_hand: {1}".format(calc,by_hand))

calculated: [ 9  7 -4  9] by_hand: [9, 7, -4, 9]


### 2.2) &nbsp;&nbsp; $\vec{u} - \vec{v} = $  

In [53]:
import numpy as np
u = np.asarray([6,2,-3,5])
v = np.asarray([3,5,-1,4])

calc = np.subtract(u,v) 
by_hand = [(6-3), (2-5), (-3--1), (5-4)]

print("calculated: {0} by_hand: {1}".format(calc,by_hand))

calculated: [ 3 -3 -2  1] by_hand: [3, -3, -2, 1]


### 2.3) &nbsp;&nbsp;  $a\vec{u}=$

In [55]:
import numpy as np
a = 6
u = np.asarray([6,2,-3,5])

calc = np.multiply(a,u) 
by_hand = [(6*6), (6*2), (6*-3), (6*5)]

print("calculated: {0} by_hand: {1}".format(calc,by_hand))

calculated: [ 36  12 -18  30] by_hand: [36, 12, -18, 30]


### 2.4) &nbsp;&nbsp; $\vec{u}\cdotp\vec{v} =$  


In [56]:
import numpy as np
u = np.asarray([6,2,-3,5])
v = np.asarray([3,5,-1,4])

calc = np.dot(u,v) 
by_hand = (6*3) + (2*5) + (-3*-1) + (5*4)

print("calculated: {0} by_hand: {1}".format(calc,by_hand))

calculated: 51 by_hand: 51


### 2.5) &nbsp;&nbsp;  $\|\vec{u}\| = $

In [36]:
import math
from numpy import linalg as LA
u = np.asarray([6,2,-3,5])

calc = LA.norm(u)

mag = lambda x : math.sqrt(sum(i**2 for i in x))
by_hand= mag(u)

print("calculated: {0} by_hand: {1}".format(calc,by_hand)) 

calculated: 8.602325267042627 by_hand: 8.602325267042627


***

# 3. Matrix Operations
Evaluate each of the following expressions, if it is defined; else fill in with ”not defined.” Do your work by hand on scratch paper.


### 3.1) A + C

In [61]:
import numpy as np
A = np.asarray([[1,2,3],[2,7,4]])     # 2x3
C = np.asarray([[5,-1],[9,1],[6,0]])  # 3x2

# Not going to work as  addition/subtraction require matrices of the same dimensions



### 3.2) A - C$^T$

In [14]:
import numpy as np
A = np.asarray([[1,2,3],[2,7,4]])
C = np.asarray([[5,-1],[9,1],[6,0]])

calc = A-C.transpose() 
by_hand = [ [(1-5), (2-9), (3-6)], [(2--1), (7-1), (4-0)]]


print("calc: {0} \n by_hand: {1}".format(calc,by_hand)) 




calc: [[-4 -7 -3]
 [ 3  6  4]] 
 by_hand: [[-4, -7, -3], [3, 6, 4]]


### 3.3) C$^T$ + 3D

In [16]:
import numpy as np
C = np.asarray([[5,-1],[9,1],[6,0]])
D = np.asarray([[3,-2,-1],[1,2,3]])

calc = C.transpose() + 3*D
# by hand done in in notebook: https://www.dropbox.com/s/p6qqifksa4zckcn/Metis-Linear-Algebra-3-3.jpg?dl=0

print(calc)




[[14  3  3]
 [ 2  7  9]]


### 3.4) BA

In [37]:
import numpy as np
B = np.asarray([[1,-1],[0,1]])    # 2x2
A = np.asarray([[1,2,3],[2,7,4]]) # 2x3
B*A
# Shape will not work


ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

### 3.5) BA$^T$

In [43]:
import numpy as np
B = np.asarray([[1,-1],[0,1]])
A = np.asarray([[1,2,3],[2,4,7]])
calc = B * A.transpose()

# Shapes are wrong. Won't work 



ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 